services:
  - type: web
    name: experiment-albena
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SECRET_KEY
        generateValue: true
      - key: RESULTS_GITHUB_REPOSITORY
        value: pi2-beep/albena_experiment_results
      - key: RESULTS_GITHUB_SSH_KEY
        sync: false
